version: "2.4"

services:
  display:
    build:
      context: .
    image: 192.168.50.250:5000/shark-develop:display-amd64-dev
    restart: always
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    runtime: nvidia
    working_dir: /opt/shark_display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/repos/shark_display:/opt/shark_display
      - ~/.gitconfig:/home/dev/.gitconfig
      - ~/.config/nvim:/home/dev/.config/nvim
      - ~/.config/github-copilot:/home/dev/.config/github-copilot
      - ~/.local/state/nvim:/home/dev/.local/state/nvim
      - ~/.local/share/nvim:/home/dev/.local/share/nvim
      - ~/.cache/nvim:/home/dev/.cache/nvim
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - "DISPLAY=$DISPLAY"
      - ROS_DISCOVERY_SERVER=0.0.0.0:11811
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: ["sleep", "infinity"]
