services:
  validation-tool:
    image: 192.168.50.250:5000/shark-develop:validation-tool-amd64-dev
    privileged: true
    container_name: validation-tool
    network_mode: host
    ipc: host
    pid: host
    environment:
      - ROS_DISCOVERY_SERVER=0.0.0.0:11811
      - DISPLAY=${DISPLAY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    working_dir: /opt/shark_validation_tool
    volumes:
      - ~/repos/shark_validation_tool:/opt/shark_validation_tool
      - ~/.gitconfig:/home/dev/.gitconfig
      - ~/.config/lazygit:/home/dev/.config/lazygit
      - ~/.config/nvim:/home/dev/.config/nvim
      - ~/.config/github-copilot:/home/dev/.config/github-copilot
      - ~/.local/state/nvim:/home/dev/.local/state/nvim
      - ~/.local/share/nvim:/home/dev/.local/share/nvim
      - ~/.cache/nvim:/home/dev/.cache/nvim
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["sleep", "infinity"]

