version: "3.7"

services:
  nvim:
    build:
      dockerfile: "Dockerfile"
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
      context: .
    volumes:
      - ${HOME}/.config/nvim:/root/.config/nvim
    command: ["sleep", "infinity"]
