version: "3.7"

services:
  nvim:
    build:
      dockerfile: "Dockerfile"
      context: .
    image: robotics-deployment:dev
    volumes:
      - .:/root/nvim
      - ~/.config/lvim:/root/.config/lvim
      - ~/.local/state/lvim:/root/.local/state/lvim
      - ~/.local/share/lvim:/root/.local/share/lvim
      - ~/.local/share/lunarvim:/root/.local/share/lunarvim
    command: ["sleep", "infinity"]
